Repository open-io/oio-sds, pull requests merged in 2018-11, with the labels that each got.

#1596 proxy: handle deadline during long listing requests
  proxy/m2_actions.c
Labels: bug :scream:, language:C, priority:1 :goberserk:

#1599 lifecycle: Check the current object with the versions
  oio/container/lifecycle.py
  tests/functional/container/test_lifecycle.py
Labels: bug :scream:

#1601 oio-blob-rebuilder: Minor fixes
  oio/rebuilder/blob_rebuilder.py
Labels: bug :scream:

#1604 Python API: fix bootstrap of meta2 rdir databases
  oio/rdir/client.py
Labels: bug :scream:, language:python :snake:

#1603 Add a utility to index already existing meta2 databases on disk
  bin/oio-meta2-indexer
  etc/meta2-indexer.conf.sample
  oio/blob/utils.py
  oio/common/constants.py
  oio/directory/indexer.py
  oio/rdir/client.py
  setup.cfg
  tests/functional/content/test_service_id.py
  tests/functional/directory/test_indexer.py
  tests/functional/event/test_events_emission.py
  tests/utils.py
Labels: enhancement :sparkles:, language:python :snake:

#1614 Improve error messages when quorum is not reached
  sqliterepo/replication.c
Labels: Logging :scroll:, language:C

#1622 Python API: do not try to balance meta1 services when zero-scored
  oio/directory/meta0.py
Labels: bug :scream:, language:python :snake:
