Repository open-io/oio-sds, pull requests merged in 2018-02, with the labels that each got.

#1359 Python API: create NoMatchFound exception for RegexContainerBuilder
  oio/common/autocontainer.py
  tests/unit/common/test_autocontainer.py
Labels: language:python

#1362 sqliterepo: Avoid a possible starvation under concurrency conditions
  sqliterepo/gridd_client_pool.c
Labels: enhancement, language:C

#1366 oio-bootstrap: Avoid restarting failed services during the tests
  tools/oio-bootstrap.py
Labels: priority:4
