Repository open-io/oio-sds, pull requests merged in 2018-06, with the labels that each got.

#1485 server: Ease the integration with prometheus exporters
  server/transport_gridd.c
Labels: enhancement :sparkles:, language:C, priority:4 :suspect:

#1487 Python API: include netloc in urllib3 errors messages
  oio/api/base.py
  oio/blob/client.py
  oio/common/http.py
Labels: enhancement :sparkles:

#1490 Python API: fix account client encoding
  oio/account/client.py
Labels: bug :scream:, language:python :snake:

#1493 sqliterepo/election: Fix the detection of Rogue nodes
  sqliterepo/election.c
Labels: bug :scream:, language:C, priority:1 :goberserk:
