Repository open-io/oio-sds, pull requests merged in 2018-03, with the labels that each got.

#1373 Fix logic error in 'openio directory bootstrap'
  oio/cli/admin/directory.py
  tools/oio-reset.sh
Labels: bug :scream:, language:python :snake:, priority:3 :rage1:

#1368 Python API: display request ID in more warning messages
  oio/api/io.py
Labels: Logging :scroll:, language:python :snake:

#1380 python: Force the location to be instances of 'str'
  oio/directory/meta0.py
Labels: bug :scream:, language:python :snake:, priority:1 :goberserk:

#1387 Add rawx fast copy
  rawx-apache2/src/rawx_repository.c
  tests/functional/blob/test_blob.py
Labels: enhancement :sparkles:, language:C, priority:1 :goberserk:

#1393 Fix the asssignation of RDIR services
  oio/rdir/client.py
Labels: enhancement :sparkles:, language:python :snake:, priority:1 :goberserk:

#1394 Fix and document the automatic connection limits
  Variables.md
  conf.json
  sqlx/sqlx_service.c
Labels: language:C, priority:4 :suspect:

#1396 Parallelize the rebuilding of the chunks
  bin/oio-blob-rebuilder
  oio/blob/rebuilder.py
Labels: enhancement :sparkles:, language:python :snake:, priority:2 :rage4:

#1397 Python API: improve pyeclib errors
  oio/common/storage_method.py
Labels: Logging :scroll:, enhancement :sparkles:, language:python :snake:

#1391 Python API, CLI: Purge container
  oio/api/object_storage.py
  oio/cli/storage/container.py
  setup.cfg
  tests/functional/content/test_content_versioning.py
Labels: enhancement :sparkles:, language:python :snake:, priority:3 :rage1:

#1398 tests/functional: Skip 3 test cases on public CI
  .travis.yml
  tests/functional/cli/admin/test_cluster.py
  tests/functional/container/test_container_backup.py
  tests/utils.py
  tox.ini
Labels: enhancement :sparkles:, language:python :snake:, priority:3 :rage1:

#1408 Python API: allow sourcing object data from iterable
  oio/api/object_storage.py
  tests/unit/api/test_objectstorage.py
  tests/unit/content/test_content.py
Labels: enhancement :sparkles:, language:python :snake:

#1409 sqliterepo: Write only on the master
  sqliterepo/replication_dispatcher.c
Labels: bug :scream:, language:C, priority:1 :goberserk:

#1410 oio-event-agent: Do not retry failed push/delete to a rdir
  oio/event/filters/volume_index.py
Labels: enhancement :sparkles:, language:python :snake:, priority:3 :rage1:

#1411 oio-account-server: Minimal access log for read-only requests
  oio/account/server.py
Labels: enhancement :sparkles:, language:python :snake:, priority:3 :rage1:

#1416 oio-proxy: Fix the retry behavior on container delete
  proxy/m2_actions.c
Labels: enhancement :sparkles:, language:C, priority:2 :rage4:

#1417 Python API: improve exception handling
  oio/api/ec.py
  oio/api/io.py
  oio/api/replication.py
  oio/common/exceptions.py
  oio/common/green.py
  tests/unit/api/test_ec.py
  tests/unit/api/test_io.py
Labels: enhancement :sparkles:, language:python :snake:
