Repository open-io/oio-sds, pull requests merged in 2018-05, with the labels that each got.

#1442 Send the content ID to create an object
  core/oiourl.h
  core/url.c
  meta2v2/meta2_backend.c
  meta2v2/meta2_utils.c
  oio/api/object_storage.py
  oio/container/client.py
  tests/functional/api/test_objectstorage.py
  tests/functional/m2_filters/test_filters.py
Labels: bug :scream:, language:python :snake:

#1466 oio-reset: Cleanup the datadir when explicitly configured
  tools/oio-reset.sh
Labels: enhancement :sparkles:, priority:4 :suspect:

#1473 sqliterepo: fix a memory leak
  sqliterepo/synchro.c
Labels: bug :scream:, language:C, priority:2 :rage4:

#1475 sqliterepo: Lazily create $repo/tmp when missing
  sqliterepo/replication_dispatcher.c
Labels: enhancement :sparkles:, language:C, priority:4 :suspect:

#1476 sqliterepo/election: Ensure a deadline in background threads
  sqliterepo/election.c
Labels: bug :scream:, language:C, priority:2 :rage4:

#1477 sqliterepo/election: Resolve the peers from the reference
  sqliterepo/election.c
Labels: enhancement :sparkles:, language:C, priority:3 :rage1:

#1478 sqliterepo/dispatcher: Remove useless calls
  sqliterepo/replication_dispatcher.c
Labels: enhancement :sparkles:, language:C, priority:3 :rage1:
