Repository open-io/oio-sds, pull requests merged in 2018-04, with the labels that each got.

#1422 Decache M2_PREP data when freezing a container
  meta2v2/meta2_backend.c
Labels: language:C, priority:3 :rage1:

#1423 Rebase and merge #1419
  oio/common/wsgi.py
Labels: enhancement :sparkles:, language:python :snake:, priority:3 :rage1:

#1430 proxy: Mangle the DB name for /admin/* when type=meta1
  Variables.CMakeFile
  Variables.md
  Variables.md.inc
  conf.json
  meta1v2/meta1_backend.c
  meta1v2/meta1_backend_internals.h
  proxy/sqlx_actions.c
Labels: bug :scream:, language:C, priority:1 :goberserk:

#1428 events: Make configurable the buffering delay
  Variables.md
  conf.json
  events/oio_events_queue.c
  events/oio_events_queue.h
  events/oio_events_queue_beanstalkd.c
  events/oio_events_queue_buffer.c
  events/oio_events_queue_buffer.h
  events/oio_events_queue_fanout.c
  events/oio_events_queue_zmq.c
Labels: enhancement :sparkles:, language:C, priority:4 :suspect:

#1443 Python API: allow disabling client-side chunk checksums
  oio/api/ec.py
  oio/api/io.py
  oio/api/object_storage.py
  oio/api/replication.py
  oio/common/constants.py
  tests/unit/api/__init__.py
  tests/unit/api/test_ec.py
  tests/unit/api/test_replication.py
Labels: enhancement :sparkles:, language:python :snake:

#1448 rawx, sqliterepo: replace strncpy by g_strlcpy
  rawx-apache2/src/mod_dav_rawx.c
  sqliterepo/election.c
Labels: language:C

#1451 sqliterepo/synchro: Dump the duration of the calls to ZK
  sqliterepo/synchro.c
Labels: enhancement :sparkles:, language:C, priority:2 :rage4:

#1452 oio-reset: Allow a specific data directory for the services
  tools/oio-bootstrap.py
  tools/oio-reset.sh
Labels: enhancement :sparkles:, priority:4 :suspect:

#1456 Python API: fix chunk full_path conversion
  oio/common/http.py
Labels: language:python :snake:
