Repository open-io/oio-sds, pull requests merged in 2018-09, with the labels that each got.

#1549 Adapt to recent libattr
  CMakeLists.txt
  metautils/lib/volume_lock.c
  rawx-lib/src/attr_handler.c
Labels: language:C, priority:4 :suspect:

#1550 conscience-agent: close connection to avoid keepalive issues
  oio/common/http_urllib3.py
  oio/conscience/checker/http.py
  oio/conscience/stats/http.py
Labels: bug :scream:, language:python :snake:

#1557 Python API: close chunks download connection
  oio/api/io.py
  oio/common/storage_functions.py
Labels: bug :scream:, language:python :snake:, priority:2 :rage4:

#1558 Python API: do not crash RegexContainerBuilder on empty capture groups
  oio/common/autocontainer.py
Labels: language:python :snake:

#1553 rawx: Implement beanstalkd client
  .travis.yml
  rawx/beanstalk.go
  rawx/main.go
  rawx/notifier.go
Labels: language:Golang

#1560 event: Select the alias correctly
  meta2v2/meta2_filters_action_content.c
Labels: bug :scream:, language:C, priority:3 :rage1:

#1563 CLI: fix 'directory decommission'
  oio/cli/directory/directory.py
  oio/directory/meta0.py
Labels: bug :scream:, language:python :snake:
