Repository open-io/oio-sds, pull requests merged in 2018-10, with the labels that each got.

#1566 Python API, CLI: document container snapshots
  oio/api/object_storage.py
  oio/cli/container/container.py
Labels: documentation :book:

#1570 rawx: send events to the appropriate tube
  rawx/notifier.go
Labels: bug :scream:, language:Golang

#1572 CLI: fix 'openio object list --auto --no-paging'
  oio/account/server.py
  oio/cli/object/object.py
Labels: bug :scream:, language:python :snake:, priority:1 :goberserk:

#1576 CLI: tolerate errors while listing objects from autocontainers
  oio/cli/object/object.py
Labels: enhancement :sparkles:, language:python :snake:, priority:4 :suspect:

#1577 oio-blob-rebuilder: Use rebuilder ID to identify the rebuilt chunks
  oio/rebuilder/blob_rebuilder.py
Labels: enhancement :sparkles:

#1589 CLI: document 'object link' command
  oio/cli/object/object.py
Labels: documentation :book:
