Repository open-io/oio-sds, pull requests merged in 2019-03, with the labels that each got.

#1690 sqliterepo: minor fixes
  sqliterepo/election.c
Labels: bug :scream:, language:C, priority:3 :rage1:

#1694 sqliterepo/election: Fix an ugly but harmless memory management
  sqliterepo/election.c
Labels: bug :scream:, language:C, priority:4 :suspect:

#1695 oio-reset: Stop calling zk-reset.py
  tools/oio-reset.sh
Labels: enhancement :sparkles:, priority:4 :suspect:

#1711 account: fix filtering when more than 1000 containers
  oio/account/backend.py
  oio/account/client.py
  oio/api/object_storage.py
Labels: bug :scream:, language:python :snake:, priority:1 :goberserk:

#1715 Make sure that meta1 are started before assigning rdir services
  tools/oio-reset.sh
Labels: bug :scream:, priority:2 :rage4:

#1710 No dump if database is corrupt
  sqliterepo/repository.c
Labels: bug :scream:, priority:4 :suspect:

#1709 Go rawx: Allow to read old chunks
  rawx/chunk_info.go
  tests/functional/blob/test_blob.py
  tests/functional/blob/test_rebuilder.py
Labels: enhancement :sparkles:
