Repository open-io/oio-sds, pull requests merged in 2019-10, with the labels that each got.

#1902 Fix prefixes of meta0 list
  oio/directory/meta0.py
  proxy/admin_actions.c
  tests/functional/directory/test_prefixmapping.py
Labels: bug :scream:

#1903 blob-rebuilder: Fix reuse of beanstalkd connections
  oio/rebuilder/blob_rebuilder.py
Labels: bug :scream:

#1907 rawx: log bad requests, enhance log format
  rawx-apache2/src/rawx_chunk_update.c
  rawx-apache2/src/rawx_repo_core.c
  rawx-apache2/src/rawx_repository.c
  tools/oio-bootstrap.py
Labels: Logging :scroll:, enhancement :sparkles:, language:C

#1909 Allow to read object with duplicated position
  oio/api/object_storage.py
  oio/common/storage_functions.py
  oio/content/ec.py
  oio/content/plain.py
  tests/unit/api/test_objectstorage.py
Labels: enhancement :sparkles:

#1911 Python API: improve error message aggregation on failed EC download
  oio/api/ec.py
  oio/api/io.py
  oio/api/object_storage.py
Labels: bug :scream:, language:python :snake:

#1913 CLI: fix container list with non-ASCII characters
  oio/common/utils.py
  oio/directory/indexer.py
  tests/functional/cli/container/test_container.py
  tests/utils.py
Labels: bug :scream:, language:python :snake:

#1912 ECD: Close the stream after reading a metachunk
  oio/ecd/app.py
Labels: bug :scream:, priority:2 :rage4:
