Repository open-io/oio-sds, pull requests merged in 2019-07, with the labels that each got.

#1824 Retry failed rebuild jobs, with a delay
  bin/oio-blob-rebuilder
  oio/rebuilder/blob_rebuilder.py
  oio/rebuilder/rebuilder.py
Labels: enhancement :sparkles:, language:python :snake:

#1827 blob-rebuilder: implement --rdir-timeout parameter
  bin/oio-blob-rebuilder
  oio/cli/volume/client.py
  oio/cli/volume/volume.py
  oio/rebuilder/blob_rebuilder.py
Labels: language:python :snake:

#1833 Get rid of the httpd-based rawx
  .travis.yml
  CMakeLists.txt
  etc/bootstrap-option-go-rawx.yml
  rawx-apache2/httpd.conf.sample
  rawx-apache2/src/CMakeLists.txt
  rawx-apache2/src/mod_dav_rawx.c
  rawx-apache2/src/mod_dav_rawx.h
  rawx-apache2/src/rawx_bucket.c
  rawx-apache2/src/rawx_bucket.h
  rawx-apache2/src/rawx_chunk_update.c
  rawx-apache2/src/rawx_config.h
  rawx-apache2/src/rawx_config_stats.c
  rawx-apache2/src/rawx_event.c
  rawx-apache2/src/rawx_event.h
  rawx-apache2/src/rawx_internals.c
  rawx-apache2/src/rawx_internals.h
  rawx-apache2/src/rawx_properties.c
  rawx-apache2/src/rawx_repo_core.c
  rawx-apache2/src/rawx_repo_core.h
  rawx-apache2/src/rawx_repository.c
  rawx-apache2/src/rawx_req_info.c
  rawx-lib/src/CMakeLists.txt
  rawx-lib/src/attr_handler.c
  rawx-lib/src/compression.c
  rawx-lib/src/compression.h
  rawx-lib/src/rawx.h
  rawx-lib/src/zlib_compress.c
  rawx-lib/tools/CMakeLists.txt
  rawx-lib/tools/gs_compress.c
  rawx-lib/tools/gs_rawx_tools.h
  rawx-lib/tools/gs_uncompress.c
  tools/oio-bootstrap.py
  tools/oio-test-suites.sh
Labels: duplicate, language:C, priority:4 :suspect:

#1836 Drop the sqlx service
  core/oiodir.h
  etc/bootstrap-preset-MINIMAL.yml
  etc/bootstrap-preset-fullrepli.yml
  etc/bootstrap-preset-smallrepli.yml
  etc/service-watch.yml
  meta2v2/meta2_server.c
  metautils/lib/metautils_macros.h
  oio/cli/admin/service_config.py
  oio/cli/admin/service_info.py
  oio/zk/client.py
  proxy/common.c
  sqliterepo/replication_dispatcher.c
  sqliterepo/replication_dispatcher.h
  sqliterepo/repository.c
  sqliterepo/synchro.h
  sqlx/CMakeLists.txt
  sqlx/sqlx_client.c
  sqlx/sqlx_client.h
  sqlx/sqlx_client_direct.c
  sqlx/sqlx_client_direct.h
  sqlx/sqlx_client_internals.h
  sqlx/sqlx_client_local.c
  sqlx/sqlx_client_local.h
  sqlx/sqlx_server.c
  sqlx/sqlx_service.c
  sqlx/sqlx_service.h
  sqlx/tool_sqlx.c
  tests/common/test_sqlx_abstract.c
  tests/func/CMakeLists.txt
  tests/func/test_sqlx_client.c
  tests/functional/cli/admin/test_service_config.py
  tests/functional/directory/test_meta2.py
  tests/unit/CMakeLists.txt
  tests/unit/test_sqlx_client.c
  tools/oio-bootstrap.py
  tools/oio-reset.sh
  tools/oio-sds.pc.in
Labels: enhancement :sparkles:, language:C, priority:4 :suspect:

#1830 oio-crawler-integrity: report missing chunk positions
  oio/cli/admin/item_check.py
  oio/cli/admin/item_rebuild.py
  oio/common/tool.py
  oio/crawler/integrity.py
  oio/event/beanstalk.py
  tests/functional/cli/admin/test_item_check.py
  tests/functional/cli/admin/test_item_rebuild.py
Labels: bug :scream:, language:python :snake:

#1838 blob-mover: Allow to exclude some rawx
  bin/oio-blob-mover
  etc/blob-mover.conf-sample
  oio/blob/mover.py
  oio/content/content.py
Labels: enhancement :sparkles:, priority:3 :rage1:

#1845 mover: Allow to move only chunk whose size is in a range
  bin/oio-blob-mover
  oio/blob/mover.py
Labels: enhancement :sparkles:, language:python :snake:, priority:1 :goberserk:

#1846 Set to "on" the default of "proxy.prefer.slave_for_read"
  Variables.md
  conf.json
Labels: enhancement :sparkles:, language:C, priority:1 :goberserk:
