Repository open-io/oio-sds, pull requests merged in 2019-11, with the labels that each got.

#1924 Python API: Fix ratelimit
  oio/common/green.py
Labels: bug :scream:

#1904 Remove ZooKeeper watches before deleting nodes
  sqliterepo/election.c
  sqliterepo/synchro.c
  sqliterepo/synchro.h
Labels: enhancement :sparkles:

#1935 Prevent from writing simultaneously on same socket
  oio/api/ec.py
Labels: bug :scream:

#1941 sqliterepo: reset elections stuck in CREATING step
  Variables.CMakeFile
  Variables.md
  conf.json
  sqliterepo/election.c
Labels: bug :scream:, language:C
