Repository open-io/oio-sds, pull requests merged in 2019-02, with the labels that each got.

#1660 CI: Split a long job
  .travis.yml
Labels: enhancement :sparkles:, priority:4 :suspect:

#1662 cli: Remove the `--no-rdir` from `directory bootstrap`
  oio/cli/directory/directory.py
Labels: enhancement :sparkles:, language:python :snake:, priority:4 :suspect:

#1661 sqliterepo: Faster exit of services
  sqliterepo/election.c
  sqliterepo/election.h
  sqlx/sqlx_service.c
Labels: enhancement :sparkles:, language:C, priority:4 :suspect:

#1671 blob-improver: do not crash when fullpath is not encodable
  oio/rebuilder/blob_improver.py
Labels: bug :scream:, language:python :snake:

#1678 proxy: Decache stale service locations more often
  proxy/common.c
  proxy/common.h
  proxy/m2_actions.c
Labels: bug :scream:, language:C, priority:3 :rage1:

#1681 CLI: add '--min-dist' option to 'rdir bootstrap'
  oio/cli/rdir/rdir.py
  oio/common/exceptions.py
  oio/conscience/client.py
  oio/rdir/client.py
  proxy/lb_actions.c
  tests/functional/api/test_directory.py
  tests/unit/common/test_exceptions.py
Labels: enhancement :sparkles:, language:python :snake:

#1686 core: Explicit the value of public enums
  core/internals.h
  core/oio_sds.h
  core/oiolog.h
  core/oiourl.h
  core/oiovar.h
Labels: enhancement :sparkles:, language:C, priority:4 :suspect:

#1687 resolver: Fix the library name
  resolver/CMakeLists.txt
Labels: bug :scream:, priority:1 :goberserk:

#1685 Python API: forward timeouts, compute a deadline
  oio/account/client.py
  oio/api/object_storage.py
  oio/common/utils.py
  oio/conscience/client.py
  tests/unit/api/test_objectstorage.py
Labels: bug :scream:, language:python :snake:
