Repository open-io/oio-sds, pull requests merged in 2019-06, with the labels that each got.

#1794 Fix get_poolmanager parameters
  oio/common/http_urllib3.py
  tests/unit/api/test_utils.py
Labels: bug :scream:, language:python :snake:, priority:1 :goberserk:

#1798 Python API: fix import of eventlet.Semaphore
  oio/common/green.py
  oio/crawler/integrity.py
Labels: bug :scream:

#1796 C API: Use the same retry policy as the Python API
  core/proxy.c
Labels: language:C, priority:2 :rage4:

#1805 proxy: Fix the location comparison
  proxy/m2_actions.c
Labels: bug :scream:, language:C, priority:1 :goberserk:

#1814 Python API: rework EC upload code
  oio/api/ec.py
Labels: bug :scream:, language:python :snake:

#1816 Python API: report EC chunks errors only once
  oio/api/ec.py
Labels: bug :scream:, language:python :snake:

#1810 Configure event-agent connection pool
  etc/event-handlers.conf-sample
  oio/blob/client.py
  oio/common/http_urllib3.py
  oio/event/filters/content_cleaner.py
  tools/oio-bootstrap.py
Labels: language:python :snake:

#1821 conf: Manage well the modifiers on second-wide (epoch) time variables
  confgen.py
  core/oiovar.h
  core/var.c
Labels: bug :scream:, language:C, language:python :snake:, priority:3 :rage1:

#1822 oio-blob-mover: implement concurrency
  bin/oio-blob-mover
  etc/blob-mover.conf-sample
  oio/blob/mover.py
Labels: language:python :snake:
