Repository open-io/oio-sds, pull requests merged in 2019-05, with the labels that each got.

#1759 Remove obsolete legacy tools | BREAKING CHANGE
  CMakeLists.txt
  cluster/tools/CMakeLists.txt
  cluster/tools/gridcluster.c
  tools/CMakeLists.txt
  tools/oio-bootstrap.py
  tools/oio-reset.sh
  tools/oio-test-suites.sh
  tools/oio-unlock-all.sh
Labels: enhancement :sparkles:, priority:4 :suspect:

#1764 Prevent installation of urllib3 1.25
  all-requirements.txt
Labels: bug :scream:

#1786 meta1: resolve account and cname only when asked
  meta1v2/meta1_backend.h
  meta1v2/meta1_backend_services.c
  meta1v2/meta1_gridd_dispatcher.c
  meta1v2/meta1_remote.c
  metautils/lib/metautils_macros.h
  tests/unit/test_meta1_backend.c
Labels: bug :scream:, language:C

#1787 Python API: better eventlet coordination
  oio/api/ec.py
  oio/api/replication.py
Labels: enhancement :sparkles:, language:python :snake:, priority:3 :rage1:
