Repository open-io/oio-sds, pull requests merged in 2019-04, with the labels that each got.

#1719 oio-reset.sh: Fix openio command
  tools/oio-reset.sh
Labels: bug :scream:

#1726 event-agent: configure timeouts to the account service
  etc/event-handlers.conf-sample
  oio/event/filters/account_update.py
Labels: enhancement :sparkles:, language:python :snake:

#1725 CLI: display nicer KeyError messages
  oio/cli/cluster/cluster.py
  oio/cli/common/clientmanager.py
  oio/cli/directory/directory.py
  oio/cli/zk/set.py
  oio/common/configuration.py
Labels: language:python :snake:

#1751 Drop old event when updating account
  oio/event/filters/account_update.py
Labels: bug :scream:
