Repository open-io/oio-sds, pull requests merged in 2019-08, with the labels that each got.

#1850 Fix the error message indicating the need for a zk bootstrap
  meta0v2/zk_manager.c
Labels: bug :scream:, language:C, priority:4 :suspect:

#1859 Allow to place some chunks locally to the proxy
  Variables.CMakeFile
  Variables.md
  conf.json
  core/lb.c
  core/oiolb.h
  etc/bootstrap-option-chunksize-1027.yml
  etc/bootstrap-option-rss64M.yml
  etc/bootstrap-preset-EC21.yml
  etc/bootstrap-preset-ECX21.yml
  meta2v2/meta2_utils.c
  meta2v2/meta2_utils_lb.c
  meta2v2/meta2_utils_lb.h
  proxy/m2_actions.c
  tools/oio-bootstrap.py
Labels: enhancement :sparkles:, language:C, priority:1 :goberserk:

#1862 core: Fix the LB on local services
  core/lb.c
  meta2v2/meta2_utils_lb.c
  meta2v2/meta2_utils_lb.h
  metautils/lib/comm_message.c
  metautils/lib/comm_meta_reply.c
  proxy/m2_actions.c
  sqliterepo/sqlx_remote_ex.c
  tools/oio-bootstrap.py
Labels: bug :scream:, enhancement :sparkles:, language:C, priority:1 :goberserk:

#1863 oio-reset: Fix the startup detection for gridinit
  tools/oio-reset.sh
Labels: enhancement :sparkles:, priority:4 :suspect:

#1869 rawx-httpd: Remove unwanted traces
  rawx-apache2/src/mod_dav_rawx.c
  rawx-apache2/src/rawx_repo_core.c
Labels: bug :scream:, language:C, priority:2 :rage4:

#1867 Increase max request run time for sqliterepo-based services
  Variables.CMakeFile
  Variables.md
  conf.json
  server/transport_gridd.c
Labels: bug :scream:
