Repository open-io/oio-sds, pull requests merged in 2020-04, with the labels that each got.

#2018 account: make known errors less verbose
  oio/common/redis_conn.py
  oio/common/wsgi.py
Labels: Logging :scroll:, bug :scream:, language:python :snake:

#2017 Speedup the RAWX
  rawx/beanstalk.go
  rawx/buffer_pool.go
  rawx/chunk_info.go
  rawx/chunkrepo.go
  rawx/conf_reader.go
  rawx/configuration.go
  rawx/const.go
  rawx/filerepo.go
  rawx/handler_chunk.go
  rawx/handler_info.go
  rawx/handler_stat.go
  rawx/hexa.go
  rawx/logger.go
  rawx/main.go
  rawx/main_test.go
  rawx/notifier.go
  rawx/rawx.go
  rawx/repo.go
  tools/oio-rawx-harass.go
Labels: enhancement :sparkles:, language:Golang, priority:3 :rage1:

#2026 proxy: update content/create documentation
  proxy/m2_actions.c
Labels: documentation :book:
