Repository open-io/oio-sds, pull requests merged in 2020-02, with the labels that each got.

#1983 Define oio-sds merge strategy
  CONTRIBUTING.md
Labels: documentation :book:, enhancement :sparkles:

#1987 meta1: Fix behavior when reference property with empty value is set
  meta1v2/meta1_backend_properties.c
  tests/functional/api/test_directory.py
Labels: bug :scream:, language:C

#1994 Admin CLI improvements
  oio/cli/admin/service_check.py
Labels: language:python :snake:
