Repository open-io/oio-sds, pull requests merged in 2020-05, with the labels that each got.

#2042 rawx: Fix unescaped special characters in JSON events, Events config, beanstalkd concurrency
  rawx/notifier.go
Labels: bug :scream:, language:Golang, priority:1 :goberserk:

#2041 Python API: retry fetch when clues of dirty cache
  oio/api/object_storage.py
  tests/functional/api/test_objectstorage.py
Labels: language:python :snake:

#2044 Check the count of known targets to avoid segfault
  core/lb.c
  tests/functional/content/test_plain.py
Labels: bug :scream:, language:C, priority:2 :rage4:
