Repository open-io/oio-sds, pull requests merged in 2020-01, with the labels that each got.

#1965 event-agent: Encode without whitespace when forwarding an event
  oio/event/filters/notify.py
Labels: bug :scream:, language:python :snake:

#1972 CLI: check peer count before actually rebalancing meta1
  oio/cli/directory/directory.py
  setup.cfg
Labels: bug :scream:, language:python :snake:

#1978 rawx: fix behavior when chunk size attr is missing
  rawx/chunk_info.go
  tests/functional/blob/test_blob.py
Labels: bug :scream:, language:Golang, language:python :snake:

#1979 rawx: fix behavior when chunk size attr is missing (again)
  rawx/chunk_info.go
  tests/functional/blob/test_blob.py
Labels: bug :scream:, language:Golang
